# Generated by Django 5.0.2 on 2024-02-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name': 'carrera', 'verbose_name_plural': 'carreras'},
        ),
    ]
